### ISSUE TITLE
NewRelicのアカウント申請

### ISSUE THREAD

**Issue by hgsgtk** [isucon-gigawatts/isucon9-qualify#7]
登録方法 https://blog.newrelic.co.jp/developers/how-to-utilize-isucon-special-license/

https://newrelic.co.jp/resources/webinars/get_ready_for_isucon10

**Comment by po3rin** [comment]
とりあえず管理画面。user追加はメアドいただき次第追加します。

https://one.newrelic.com/launcher/nr1-core.home?pane=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5ob21lLXNjcmVlbiJ9&platform[accountId]=2826731

**Comment by hgsgtk** [comment]
hgsgtk@gmail.com

お願いします！

**Comment by po3rin** [comment]
done!!招待メール飛んだと思います

**Comment by po3rin** [comment]
あ！gcpと間違えた！reopen!!

**Comment by po3rin** [comment]
今度こそdone

**Comment by hgsgtk** [comment]
ありがとうございました！
